// <auto-generated />
using LederfestPhoto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LederfestPhoto.Migrations
{
    [DbContext(typeof(LederfestPhotoContext))]
    [Migration("20180226221726_AddChallenges")]
    partial class AddChallenges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LederfestPhoto.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("LederfestPhoto.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChallengeId");

                    b.Property<int>("Rating");

                    b.Property<Guid>("Team");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("LederfestPhoto.Models.Photo", b =>
                {
                    b.HasOne("LederfestPhoto.Models.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId");
                });
#pragma warning restore 612, 618
        }
    }
}
